### PR TITLE
Fix #165

### LINKED ISSUE #165: Jester doesn't work with asynchttpserver
For the following
```nim
import jester

routes:
  get "/hello/@name":
    resp "Hello " & @"name"
```
the first valid request like `http://127.0.0.1:5000/hello/name`
is answered and directly after this crashes `jester` with something like
```
INFO Jester is making jokes at http://127.0.0.1:5000 (all interfaces)
DEBUG GET /hello/name
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(47)       processRequest_continue
[[reraised from:
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncmacro.nim(36)       processClient_continue
asynchttpserver.nim(288) processClientIter
asyncfutures.nim(302)    read
]]
[[reraised from:
jesterTest.nim(3)        jesterTest
jester.nim(489)          serve
asyncdispatch.nim(1645)  runForever
asyncdispatch.nim(1514)  poll
asyncdispatch.nim(353)   runOnce
asyncdispatch.nim(189)   processPendingCallbacks
asyncfutures.nim(348)    :anonymous
]]
Error: unhandled exception: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Async traceback:
  jesterTest.nim(3)        jesterTest
  jester.nim(489)          serve
  asyncdispatch.nim(1645)  runForever
  asyncdispatch.nim(1514)  poll
    ## Processes asynchronous completion events
  asyncdispatch.nim(353)   runOnce
  asyncdispatch.nim(189)   processPendingCallbacks
    ## Executes pending callbacks
  asyncmacro.nim(47)       processRequest_continue
    ## Resumes an async procedure
  #[
    jesterTest.nim(3)        jesterTest
    jester.nim(489)          serve
    asyncdispatch.nim(1645)  runForever
    asyncdispatch.nim(1514)  poll
      ## Processes asynchronous completion events
    asyncdispatch.nim(353)   runOnce
    asyncdispatch.nim(189)   processPendingCallbacks
      ## Executes pending callbacks
    asyncmacro.nim(36)       processClient_continue
      ## Resumes an async procedure
    asynchttpserver.nim(288) processClientIter
    asyncfutures.nim(302)    read
  ]#
Exception message: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Exception type: [AssertionError]
```
Invalid requests work as expected.
Tested on Nim `Version 0.18.1 [Windows: amd64]; Compiled at 2018-08-26` with `jester@#head`.

### PR DESCRIPTION
**Pull request by silent-observer**
This should fix #165. I think it was because without explicit return result was initialized to nil which caused that error

### CODE REVIEW

File: jester.nim [hunk 1]
```diff
@@ -374,6 +374,9 @@ proc handleRequest(jes: Jester, httpReq: NativeRequest): Future[void] =
           respData.content,
           respData.headers
         )
+        let future = newFuture[void]()
+        complete(future)
+        return future
```
Comment (dom96) [inline jester.nim]: Hrm, indeed. You got this right. I can merge this but I would prefer this to be at the bottom of the procedure, that way it will catch all cases when no future is returned. Can you move it there?

**Comment by silent-observer** [comment]
Do you mean like that?

**Comment by dom96** [comment]
Yeah, thanks!
